export interface Country {
	label: string;
	code: string;
	short: string;
}

const countries: Country[] = [
	{ label: "Dominica", code: "+1-767", short: "DM" },
	{ label: "Dominican Republic", code: "+1-809", short: "DO" },
	{ label: "Ecuador", code: "+593", short: "EC" },
	{ label: "Egypt", code: "+20", short: "EG" },
	{ label: "El Salvador", code: "+503", short: "SV" },
	{ label: "Equatorial Guinea", code: "+240", short: "GQ" },
	{ label: "Eritrea", code: "+291", short: "ER" },
	{ label: "Estonia", code: "+372", short: "EE" },
	{ label: "Eswatini", code: "+268", short: "SZ" },
	{ label: "Ethiopia", code: "+251", short: "ET" },
	{ label: "Fiji", code: "+679", short: "FJ" },
	{ label: "Finland", code: "+358", short: "FI" },
	{ label: "France", code: "+33", short: "FR" },
	{ label: "French Guiana", code: "+594", short: "GF" },
	{ label: "French Polynesia", code: "+689", short: "PF" },
	{ label: "Gabon", code: "+241", short: "GA" },
	{ label: "Gambia", code: "+220", short: "GM" },
	{ label: "Georgia", code: "+995", short: "GE" },
	{ label: "Germany", code: "+49", short: "DE" },
	{ label: "Ghana", code: "+233", short: "GH" },
	{ label: "Gibraltar", code: "+350", short: "GI" },
	{ label: "Greece", code: "+30", short: "GR" },
	{ label: "Greenland", code: "+299", short: "GL" },
	{ label: "Grenada", code: "+1-473", short: "GD" },
	{ label: "Guam", code: "+1-671", short: "GU" },
	{ label: "Guatemala", code: "+502", short: "GT" },
	{ label: "Guinea", code: "+224", short: "GN" },
	{ label: "Guinea-Bissau", code: "+245", short: "GW" },
	{ label: "Guyana", code: "+595", short: "GY" },
	{ label: "Haiti", code: "+509", short: "HT" },
	{ label: "Honduras", code: "+504", short: "HN" },
	{ label: "Hong Kong", code: "+852", short: "HK" },
	{ label: "Hungary", code: "+36", short: "HU" },
	{ label: "Iceland", code: "+354", short: "IS" },
	{ label: "India", code: "+91", short: "IN" },
	{ label: "Indonesia", code: "+62", short: "ID" },
	{ label: "Iran", code: "+98", short: "IR" },
	{ label: "Iraq", code: "+964", short: "IQ" },
	{ label: "Ireland", code: "+353", short: "IE" },
	{ label: "Israel", code: "+972", short: "IL" },
	{ label: "Italy", code: "+39", short: "IT" },
	{ label: "Jamaica", code: "+1-876", short: "JM" },
	{ label: "Japan", code: "+81", short: "JP" },
	{ label: "Jordan", code: "+962", short: "JO" },
	{ label: "Kazakhstan", code: "+7", short: "KZ" },
	{ label: "Kenya", code: "+254", short: "KE" },
	{ label: "Kiribati", code: "+686", short: "KI" },
	{ label: "Korea (North)", code: "+850", short: "KP" },
	{ label: "Korea (South)", code: "+82", short: "KR" },
	{ label: "Kuwait", code: "+965", short: "KW" },
	{ label: "Kyrgyzstan", code: "+996", short: "KG" },
	{ label: "Laos", code: "+856", short: "LA" },
	{ label: "Latvia", code: "+371", short: "LV" },
	{ label: "Lebanon", code: "+961", short: "LB" },
	{ label: "Lesotho", code: "+266", short: "LS" },
	{ label: "Liberia", code: "+231", short: "LR" },
	{ label: "Libya", code: "+218", short: "LY" },
	{ label: "Liechtenstein", code: "+423", short: "LI" },
	{ label: "Lithuania", code: "+370", short: "LT" },
	{ label: "Luxembourg", code: "+352", short: "LU" },
	{ label: "Madagascar", code: "+261", short: "MG" },
	{ label: "Malawi", code: "+265", short: "MW" },
	{ label: "Malaysia", code: "+60", short: "MY" },
	{ label: "Maldives", code: "+960", short: "MV" },
	{ label: "Mali", code: "+223", short: "ML" },
	{ label: "Malta", code: "+356", short: "MT" },
	{ label: "Marshall Islands", code: "+692", short: "MH" },
	{ label: "Martinique", code: "+596", short: "MQ" },
	{ label: "Mauritania", code: "+222", short: "MR" },
	{ label: "Mauritius", code: "+230", short: "MU" },
	{ label: "Mayotte", code: "+262", short: "YT" },
	{ label: "Mexico", code: "+52", short: "MX" },
	{ label: "Micronesia", code: "+691", short: "FM" },
	{ label: "Moldova", code: "+373", short: "MD" },
	{ label: "Monaco", code: "+377", short: "MC" },
	{ label: "Mongolia", code: "+976", short: "MN" },
	{ label: "Montenegro", code: "+382", short: "ME" },
	{ label: "Montserrat", code: "+1-664", short: "MS" },
	{ label: "Morocco", code: "+212", short: "MA" },
	{ label: "Mozambique", code: "+258", short: "MZ" },
	{ label: "Myanmar", code: "+95", short: "MM" },
	{ label: "Namibia", code: "+264", short: "NA" },
	{ label: "Nauru", code: "+674", short: "NR" },
	{ label: "Nepal", code: "+977", short: "NP" },
	{ label: "Netherlands", code: "+31", short: "NL" },
	{ label: "New Caledonia", code: "+687", short: "NC" },
	{ label: "New Zealand", code: "+64", short: "NZ" },
	{ label: "Nicaragua", code: "+505", short: "NI" },
	{ label: "Niger", code: "+227", short: "NE" },
	{ label: "Nigeria", code: "+234", short: "NG" },
	{ label: "Niue", code: "+683", short: "NU" },
	{ label: "Norfolk Island", code: "+672", short: "NF" },
	{ label: "North Macedonia", code: "+389", short: "MK" },
	{ label: "Northern Mariana Islands", code: "+1-670", short: "MP" },
	{ label: "Norway", code: "+47", short: "NO" },
	{ label: "Oman", code: "+968", short: "OM" },
	{ label: "Pakistan", code: "+92", short: "PK" },
	{ label: "Palau", code: "+680", short: "PW" },
	{ label: "Panama", code: "+507", short: "PA" },
	{ label: "Papua New Guinea", code: "+675", short: "PG" },
	{ label: "Paraguay", code: "+595", short: "PY" },
	{ label: "Peru", code: "+51", short: "PE" },
	{ label: "Philippines", code: "+63", short: "PH" },
	{ label: "Pitcairn Islands", code: "+870", short: "PN" },
	{ label: "Poland", code: "+48", short: "PL" },
	{ label: "Portugal", code: "+351", short: "PT" },
	{ label: "Puerto Rico", code: "+1-787", short: "PR" },
	{ label: "Qatar", code: "+974", short: "QA" },
	{ label: "Romania", code: "+40", short: "RO" },
	{ label: "Russia", code: "+7", short: "RU" },
	{ label: "Rwanda", code: "+250", short: "RW" },
	{ label: "Réunion", code: "+262", short: "RE" },
	{ label: "Saint Barthélemy", code: "+590", short: "BL" },
	{ label: "Saint Helena", code: "+290", short: "SH" },
	{ label: "Saint Kitts and Nevis", code: "+1-869", short: "KN" },
	{ label: "Saint Lucia", code: "+1-758", short: "LC" },
	{ label: "Saint Martin", code: "+590", short: "MF" },
	{ label: "Saint Pierre and Miquelon", code: "+508", short: "PM" },
	{ label: "Saint Vincent and the Grenadines", code: "+1-784", short: "VC" },
	{ label: "Samoa", code: "+685", short: "WS" },
	{ label: "San Marino", code: "+378", short: "SM" },
	{ label: "Sao Tome and Principe", code: "+239", short: "ST" },
	{ label: "Saudi Arabia", code: "+966", short: "SA" },
	{ label: "Senegal", code: "+221", short: "SN" },
	{ label: "Serbia", code: "+381", short: "RS" },
	{ label: "Seychelles", code: "+248", short: "SC" },
	{ label: "Sierra Leone", code: "+232", short: "SL" },
	{ label: "Singapore", code: "+65", short: "SG" },
	{ label: "Sint Maarten", code: "+1-721", short: "SX" },
	{ label: "Slovakia", code: "+421", short: "SK" },
	{ label: "Slovenia", code: "+386", short: "SI" },
	{ label: "Solomon Islands", code: "+677", short: "SB" },
	{ label: "Somalia", code: "+252", short: "SO" },
	{ label: "South Africa", code: "+27", short: "ZA" },
	{ label: "South Georgia and the South Sandwich Islands", code: "+500", short: "GS" },
	{ label: "South Sudan", code: "+211", short: "SS" },
	{ label: "Spain", code: "+34", short: "ES" },
	{ label: "Sri Lanka", code: "+94", short: "LK" },
	{ label: "Sudan", code: "+249", short: "SD" },
	{ label: "Suriname", code: "+597", short: "SR" },
	{ label: "Svalbard and Jan Mayen", code: "+47", short: "SJ" },
	{ label: "Sweden", code: "+46", short: "SE" },
	{ label: "Switzerland", code: "+41", short: "CH" },
	{ label: "Syria", code: "+963", short: "SY" },
	{ label: "Taiwan", code: "+886", short: "TW" },
	{ label: "Tajikistan", code: "+992", short: "TJ" },
	{ label: "Tanzania", code: "+255", short: "TZ" },
	{ label: "Thailand", code: "+66", short: "TH" },
	{ label: "Timor-Leste", code: "+670", short: "TL" },
	{ label: "Togo", code: "+228", short: "TG" },
	{ label: "Tokelau", code: "+690", short: "TK" },
	{ label: "Tonga", code: "+676", short: "TO" },
	{ label: "Trinidad and Tobago", code: "+1-868", short: "TT" },
	{ label: "Tunisia", code: "+216", short: "TN" },
	{ label: "Turkey", code: "+90", short: "TR" },
	{ label: "Turkmenistan", code: "+993", short: "TM" },
	{ label: "Tuvalu", code: "+688", short: "TV" },
	{ label: "Uganda", code: "+256", short: "UG" },
	{ label: "Ukraine", code: "+380", short: "UA" },
	{ label: "United Arab Emirates", code: "+971", short: "AE" },
	{ label: "United Kingdom", code: "+44", short: "GB" },
	{ label: "United States", code: "+1", short: "US" },
	{ label: "Uruguay", code: "+598", short: "UY" },
	{ label: "Uzbekistan", code: "+998", short: "UZ" },
	{ label: "Vanuatu", code: "+678", short: "VU" },
	{ label: "Vatican City", code: "+39", short: "VA" },
	{ label: "Venezuela", code: "+58", short: "VE" },
	{ label: "Vietnam", code: "+84", short: "VN" },
	{ label: "Wallis and Futuna", code: "+681", short: "WF" },
	{ label: "Western Sahara", code: "+212", short: "EH" },
	{ label: "Yemen", code: "+967", short: "YE" },
	{ label: "Zambia", code: "+260", short: "ZM" },
	{ label: "Zimbabwe", code: "+263", short: "ZW" }
];

export default countries;
