import img from "@/assets/spots/jazz.jpg";
import sport from "@/assets/spot/2.jpg";
import p1 from "@/assets/spot/1.jpg";
import p2 from "@/assets/spot/2.jpg";
import p3 from "@/assets/spot/3.jpg";
import p4 from "@/assets/spot/4.jpg";
import p5 from "@/assets/spot/5.jpg";
import p6 from "@/assets/spot/6.jpg";
import type { staffMembers } from "./types";

// Mock data for spots
const spots = [
	{
		id: 1,
		name: "The Riverside Bistro",
		category: "restaurants",
		rating: 4.8,
		reviews: 243,
		price: "$$",
		description: "Elegant dining with river views and fresh local ingredients",
		image:
			"https://readdy.ai/api/search-image?query=elegant%20restaurant%20interior%20with%20river%20view%2C%20warm%20ambient%20lighting%2C%20modern%20minimalist%20decor%2C%20beautifully%20plated%20food%2C%20professional%20photography%2C%20high-end%20dining%20experience%20with%20simple%20white%20background&width=600&height=400&seq=1&orientation=landscape",
		isOpen: true,
		isFeatured: true,
	},
	{
		id: 2,
		name: "Skyline Lounge",
		category: "bars",
		rating: 4.6,
		reviews: 187,
		price: "$$$",
		description: "Rooftop cocktail bar with panoramic city views",
		image:
			"https://readdy.ai/api/search-image?query=modern%20rooftop%20bar%20with%20city%20skyline%20view%2C%20elegant%20cocktails%2C%20ambient%20evening%20lighting%2C%20stylish%20patrons%2C%20luxurious%20seating%20area%2C%20professional%20photography%20with%20simple%20white%20background&width=600&height=400&seq=2&orientation=landscape",
		isOpen: true,
		isFeatured: true,
	},
	{
		id: 3,
		name: "Serenity Spa & Wellness",
		category: "spas",
		rating: 4.9,
		reviews: 312,
		price: "$$$$",
		description: "Luxury spa treatments in a tranquil environment",
		image:
			"https://readdy.ai/api/search-image?query=luxurious%20spa%20interior%20with%20tranquil%20ambiance%2C%20massage%20tables%20with%20white%20linens%2C%20subtle%20lighting%2C%20bamboo%20elements%2C%20water%20features%2C%20zen%20atmosphere%2C%20professional%20photography%20with%20simple%20white%20background&width=600&height=400&seq=3&orientation=landscape",
		isOpen: true,
		isFeatured: true,
	},
	{
		id: 4,
		name: "The Coffee Atelier",
		category: "cafes",
		rating: 4.5,
		reviews: 208,
		price: "$",
		description: "Artisanal coffee shop with house-roasted beans",
		image:
			"https://readdy.ai/api/search-image?query=cozy%20coffee%20shop%20interior%20with%20wooden%20tables%2C%20barista%20preparing%20coffee%2C%20latte%20art%2C%20pastry%20display%2C%20warm%20lighting%2C%20hipster%20atmosphere%2C%20customers%20working%20on%20laptops%2C%20professional%20photography%20with%20simple%20white%20background&width=600&height=400&seq=4&orientation=landscape",
		isOpen: true,
		isFeatured: true,
	},
	{
		id: 5,
		name: "Zen Garden Restaurant",
		category: "restaurants",
		rating: 4.7,
		reviews: 156,
		price: "$$$",
		description: "Japanese fusion cuisine in a serene garden setting",
		image:
			"https://readdy.ai/api/search-image?query=japanese%20restaurant%20with%20zen%20garden%2C%20modern%20interior%20design%2C%20traditional%20elements%2C%20sushi%20presentation%2C%20ambient%20lighting%2C%20peaceful%20dining%20atmosphere%2C%20professional%20photography%20with%20simple%20white%20background&width=600&height=400&seq=5&orientation=landscape",
		isOpen: true,
		isFeatured: true,
	},
	{
		id: 6,
		name: "The Vintage Wine Bar",
		category: "bars",
		rating: 4.8,
		reviews: 198,
		price: "$$$$",
		description: "Exclusive wine bar featuring rare vintages",
		image:
			"https://readdy.ai/api/search-image?query=elegant%20wine%20bar%20interior%2C%20wine%20bottle%20display%2C%20intimate%20lighting%2C%20sophisticated%20atmosphere%2C%20wine%20tasting%20setup%2C%20professional%20photography%20with%20simple%20white%20background&width=600&height=400&seq=6&orientation=landscape",
		isOpen: true,
		isFeatured: true,
	},
	{
		id: 7,
		name: "Urban Fitness Club",
		category: "gyms",
		rating: 4.6,
		reviews: 275,
		price: "$$$",
		description: "State-of-the-art fitness center with personal training",
		image:
			"https://readdy.ai/api/search-image?query=modern%20gym%20interior%20with%20luxury%20equipment%2C%20training%20area%2C%20fitness%20class%20space%2C%20motivational%20decor%2C%20bright%20lighting%2C%20professional%20photography%20with%20simple%20white%20background&width=600&height=400&seq=7&orientation=landscape",
		isOpen: true,
		isFeatured: true,
	},
	{
		id: 8,
		name: "The Art Gallery Cafe",
		category: "cafes",
		rating: 4.7,
		reviews: 167,
		price: "$$",
		description: "Contemporary cafe featuring local artists",
		image:
			"https://readdy.ai/api/search-image?query=modern%20cafe%20with%20art%20gallery%2C%20coffee%20bar%2C%20artwork%20display%2C%20creative%20atmosphere%2C%20comfortable%20seating%2C%20professional%20photography%20with%20simple%20white%20background&width=600&height=400&seq=8&orientation=landscape",
		isOpen: true,
		isFeatured: true,
	},
	{
		id: 9,
		name: "Harmony Day Spa",
		category: "spas",
		rating: 4.9,
		reviews: 223,
		price: "$$$",
		description: "Holistic wellness treatments and relaxation",
		image:
			"https://readdy.ai/api/search-image?query=luxury%20spa%20interior%20with%20treatment%20rooms%2C%20relaxation%20area%2C%20natural%20elements%2C%20calming%20colors%2C%20wellness%20atmosphere%2C%20professional%20photography%20with%20simple%20white%20background&width=600&height=400&seq=9&orientation=landscape",
		isOpen: true,
		isFeatured: true,
	},
	{
		id: 10,
		name: "The Grand Bistro",
		category: "restaurants",
		rating: 4.8,
		reviews: 289,
		price: "$$$$",
		description: "Fine French cuisine in an elegant setting",
		image:
			"https://readdy.ai/api/search-image?query=luxury%20french%20restaurant%20interior%2C%20elegant%20dining%20setup%2C%20gourmet%20food%20presentation%2C%20crystal%20chandeliers%2C%20sophisticated%20atmosphere%2C%20professional%20photography%20with%20simple%20white%20background&width=600&height=400&seq=10&orientation=landscape",
		isOpen: true,
		isFeatured: true,
	},
	{
		id: 2,
		name: "Skyline Lounge",
		category: "bars",
		rating: 4.6,
		reviews: 187,
		price: "$$$",
		description: "Rooftop cocktail bar with panoramic city views",
		image:
			"https://readdy.ai/api/search-image?query=modern%20rooftop%20bar%20with%20city%20skyline%20view%2C%20elegant%20cocktails%2C%20ambient%20evening%20lighting%2C%20stylish%20patrons%2C%20luxurious%20seating%20area%2C%20professional%20photography%20with%20simple%20white%20background&width=600&height=400&seq=2&orientation=landscape",
		isOpen: true,
		isFeatured: false,
	},
	{
		id: 3,
		name: "Serenity Spa & Wellness",
		category: "spas",
		rating: 4.9,
		reviews: 312,
		price: "$$$$",
		description: "Luxury spa treatments in a tranquil environment",
		image:
			"https://readdy.ai/api/search-image?query=luxurious%20spa%20interior%20with%20tranquil%20ambiance%2C%20massage%20tables%20with%20white%20linens%2C%20subtle%20lighting%2C%20bamboo%20elements%2C%20water%20features%2C%20zen%20atmosphere%2C%20professional%20photography%20with%20simple%20white%20background&width=600&height=400&seq=3&orientation=landscape",
		isOpen: true,
		isFeatured: true,
	},
	{
		id: 4,
		name: "St. Mary's Cathedral",
		category: "churches",
		rating: 4.7,
		reviews: 156,
		price: "Free",
		description:
			"Historic cathedral with stunning architecture and stained glass",
		image:
			"https://readdy.ai/api/search-image?query=majestic%20cathedral%20interior%20with%20stunning%20stained%20glass%20windows%2C%20ornate%20architecture%2C%20wooden%20pews%2C%20altar%20with%20candles%2C%20soft%20natural%20lighting%20streaming%20through%20windows%2C%20professional%20photography%20with%20simple%20white%20background&width=600&height=400&seq=4&orientation=landscape",
		isOpen: true,
		isFeatured: false,
	},
	{
		id: 5,
		name: "The Coffee Atelier",
		category: "cafes",
		rating: 4.5,
		reviews: 208,
		price: "$",
		description: "Artisanal coffee shop with house-roasted beans",
		image:
			"https://readdy.ai/api/search-image?query=cozy%20coffee%20shop%20interior%20with%20wooden%20tables%2C%20barista%20preparing%20coffee%2C%20latte%20art%2C%20pastry%20display%2C%20warm%20lighting%2C%20hipster%20atmosphere%2C%20customers%20working%20on%20laptops%2C%20professional%20photography%20with%20simple%20white%20background&width=600&height=400&seq=5&orientation=landscape",
		isOpen: true,
		isFeatured: false,
	},
	{
		id: 6,
		name: "PowerFit Gym",
		category: "gyms",
		rating: 4.4,
		reviews: 175,
		price: "$$",
		description: "Modern fitness center with state-of-the-art equipment",
		image:
			"https://readdy.ai/api/search-image?query=modern%20gym%20interior%20with%20state-of-the-art%20equipment%2C%20people%20working%20out%2C%20bright%20lighting%2C%20clean%20design%2C%20weight%20area%2C%20cardio%20machines%2C%20motivational%20wall%20graphics%2C%20professional%20photography%20with%20simple%20white%20background&width=600&height=400&seq=6&orientation=landscape",
		isOpen: true,
		isFeatured: false,
	},
	{
		id: 7,
		name: "Fusion Kitchen",
		category: "restaurants",
		rating: 4.7,
		reviews: 231,
		price: "$$$",
		description:
			"Innovative fusion cuisine blending Asian and European flavors",
		image:
			"https://readdy.ai/api/search-image?query=modern%20restaurant%20with%20fusion%20cuisine%2C%20beautifully%20plated%20dishes%20with%20artistic%20presentation%2C%20contemporary%20interior%20design%2C%20soft%20lighting%2C%20diverse%20clientele%2C%20professional%20food%20photography%20with%20simple%20white%20background&width=600&height=400&seq=7&orientation=landscape",
		isOpen: false,
		isFeatured: true,
	},
	{
		id: 8,
		name: "Vintage Vinyl Bar",
		category: "bars",
		rating: 4.5,
		reviews: 164,
		price: "$$",
		description: "Retro-themed bar with live music and classic cocktails",
		image:
			"https://readdy.ai/api/search-image?query=retro%20bar%20with%20vinyl%20records%20on%20walls%2C%20vintage%20furniture%2C%20stage%20for%20live%20music%2C%20bartender%20mixing%20cocktails%2C%20warm%20lighting%2C%20hip%20crowd%2C%20nostalgic%20atmosphere%2C%20professional%20photography%20with%20simple%20white%20background&width=600&height=400&seq=8&orientation=landscape",
		isOpen: true,
		isFeatured: false,
	},
];

const upcomingBookings = [
	{
		id: 1,
		customerName: "John Smith",
		spotName: "Seaside Restaurant",
		date: "June 8, 2025",
		time: "7:00 PM",
		guests: 4,
		status: "confirmed",
		type: "Dinner Reservation",
	},
	{
		id: 2,
		customerName: "Emily Johnson",
		spotName: "Urban Spa Retreat",
		date: "June 9, 2025",
		time: "10:00 AM",
		guests: 1,
		status: "pending",
		type: "Massage Therapy",
	},
	{
		id: 3,
		customerName: "Michael Brown",
		spotName: "Downtown Event Hall",
		date: "June 10, 2025",
		time: "3:00 PM",
		guests: 50,
		status: "confirmed",
		type: "Corporate Meeting",
	},
	{
		id: 4,
		customerName: "Sarah Davis",
		spotName: "Rooftop Bar",
		date: "June 10, 2025",
		time: "8:30 PM",
		guests: 6,
		status: "confirmed",
		type: "Birthday Celebration",
	},
];
// Mock data for messages
const messages = [
	{
		id: 1,
		sender: "Lisa Thompson",
		avatar:
			"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20a%20smiling%20woman%20with%20short%20brown%20hair%2C%20business%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting%2C%20soft%20focus%2C%20corporate%20headshot%20style&width=40&height=40&seq=1&orientation=squarish",
		message:
			"Hi, I would like to know if you have availability for a corporate event next month?",
		time: "10:23 AM",
		unread: true,
	},
	{
		id: 2,
		sender: "Robert Wilson",
		avatar:
			"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20a%20middle%20aged%20man%20with%20glasses%20and%20short%20dark%20hair%2C%20business%20casual%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting%2C%20soft%20focus%2C%20corporate%20headshot%20style&width=40&height=40&seq=2&orientation=squarish",
		message:
			"Thank you for confirming my reservation. I have a question about the menu options.",
		time: "Yesterday",
		unread: false,
	},
	{
		id: 3,
		sender: "Amanda Garcia",
		avatar:
			"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20a%20young%20woman%20with%20long%20black%20hair%2C%20business%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting%2C%20soft%20focus%2C%20corporate%20headshot%20style&width=40&height=40&seq=3&orientation=squarish",
		message:
			"Is it possible to extend our booking time by an hour? We might need extra time for setup.",
		time: "Yesterday",
		unread: true,
	},
];
// Mock data for staff tasks
const staffTasks = [
	{
		id: 1,
		task: "Prepare meeting room for corporate event",
		assignee: "David Miller",
		avatar:
			"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20a%20young%20man%20with%20short%20blonde%20hair%2C%20business%20casual%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting%2C%20soft%20focus%2C%20corporate%20headshot%20style&width=40&height=40&seq=4&orientation=squarish",
		dueDate: "Today, 2:00 PM",
		priority: "high",
		status: "in-progress",
	},
	{
		id: 2,
		task: "Restock bar supplies for weekend events",
		assignee: "Jessica Lee",
		avatar:
			"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20a%20woman%20with%20medium%20length%20red%20hair%2C%20business%20casual%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting%2C%20soft%20focus%2C%20corporate%20headshot%20style&width=40&height=40&seq=5&orientation=squarish",
		dueDate: "Tomorrow, 10:00 AM",
		priority: "medium",
		status: "pending",
	},
	{
		id: 3,
		task: "Call vendors to confirm deliveries",
		assignee: "Thomas Chen",
		avatar:
			"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20an%20asian%20man%20with%20black%20hair%2C%20business%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting%2C%20soft%20focus%2C%20corporate%20headshot%20style&width=40&height=40&seq=6&orientation=squarish",
		dueDate: "June 9, 11:00 AM",
		priority: "low",
		status: "completed",
	},
	{
		id: 4,
		task: "Update event calendar on website",
		assignee: "Emma Wilson",
		avatar:
			"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20a%20young%20woman%20with%20blonde%20hair%20in%20a%20ponytail%2C%20business%20casual%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting%2C%20soft%20focus%2C%20corporate%20headshot%20style&width=40&height=40&seq=7&orientation=squarish",
		dueDate: "June 10, 4:00 PM",
		priority: "medium",
		status: "pending",
	},
];
// Mock data for staff management
const staffMembers: staffMembers[] = [
	{
		key: "1",
		name: "David Miller",
		avatar:
			"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20a%20young%20man%20with%20short%20blonde%20hair%2C%20business%20casual%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting%2C%20soft%20focus%2C%20corporate%20headshot%20style&width=40&height=40&seq=8&orientation=squarish",
		role: "Manager",
		spots: ["Seaside Restaurant", "Rooftop Bar"],
		status: "Active",
		lastActive: "10 minutes ago",
	},
	{
		key: "2",
		name: "Jessica Lee",
		avatar:
			"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20a%20woman%20with%20medium%20length%20red%20hair%2C%20business%20casual%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting%2C%20soft%20focus%2C%20corporate%20headshot%20style&width=40&height=40&seq=9&orientation=squarish",
		role: "Event Host",
		spots: ["Downtown Event Hall"],
		status: "Active",
		lastActive: "2 hours ago",
	},
	{
		key: "3",
		name: "Thomas Chen",
		avatar:
			"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20an%20asian%20man%20with%20black%20hair%2C%20business%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting%2C%20soft%20focus%2C%20corporate%20headshot%20style&width=40&height=40&seq=10&orientation=squarish",
		role: "Support Staff",
		spots: ["Urban Spa Retreat"],
		status: "Inactive",
		lastActive: "2 days ago",
	},
	{
		key: "4",
		name: "Emma Wilson",
		avatar:
			"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20a%20young%20woman%20with%20blonde%20hair%20in%20a%20ponytail%2C%20business%20casual%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting%2C%20soft%20focus%2C%20corporate%20headshot%20style&width=40&height=40&seq=11&orientation=squarish",
		role: "Manager",
		spots: ["Rooftop Bar"],
		status: "Active",
		lastActive: "1 day ago",
	},
	{
		key: "5",
		name: "Michael Rodriguez",
		avatar:
			"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20a%20latino%20man%20with%20short%20dark%20hair%2C%20business%20casual%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting%2C%20soft%20focus%2C%20corporate%20headshot%20style&width=40&height=40&seq=12&orientation=squarish",
		role: "Support Staff",
		spots: ["Seaside Restaurant", "Downtown Event Hall"],
		status: "Pending",
		lastActive: "Never",
	},
];
// Mock data for spots with followers
const mySpots = [
	{
		id: 1,
		name: "Seaside Restaurant",
		type: "Restaurant",
		location: "Oceanfront Drive, Miami",
		image: sport,
		bookings: 24,
		rating: 4.8,
		followers: 1250,
		isFollowed: true,
		revenue: "$24,500",
		status: "active",
		photos: [p1, p2, p3, p4, p5, p6],
		policies: {
			cancellation: "60 days notice required",
			insurance: "Required",
			cleaning: "$300 fee",
		},
		pricing: {
			base: "$400/hour",
			minimum: "$2000",
			deposit: "50%",
		},
		hours: [
			{ day: "monday", time: "4:00 PM - 12:00 AM" },
			{ day: "tuesday", time: "4:00 PM - 12:00 AM" },
			{ day: "wednesday", time: "4:00 PM - 1:00 AM" },
			{ day: "thursday", time: "4:00 PM - 1:00 AM" },
			{ day: "friday", time: "4:00 PM - 2:00 AM" },
			{ day: "saturday", time: "12:00 PM - 2:00 AM" },
			{ day: "sunday", time: "12:00 PM - 10:00 PM" },
		],
		address: "123 Urban Avenue, Downtown, City",
		phone: "+1 (555) 123-4567",
		website: "www.skylinerooftop.com",
		description:
			"Perched on the 20th floor with panoramic city views, Skyline Rooftop Lounge offers a sophisticated urban escape with craft cocktails, gourmet small plates, and live music events. Our open-air terrace and stylish indoor lounge create the perfect atmosphere for everything from casual happy hours to special celebrations. Known for our sunset DJ sessions and seasonal menu, we've become a favorite destination for both locals and visitors seeking an elevated social experience.",
		amenities: [
			{ name: "Outdoor Seating", icon: "fa-umbrella-beach" },
			{ name: "Live Music", icon: "fa-music" },
			{ name: "Craft Cocktails", icon: "fa-martini-glass-citrus" },
			{ name: "Reservations", icon: "fa-calendar-check" },
			{ name: "Valet Parking", icon: "fa-car" },
			{ name: "Wheelchair Accessible", icon: "fa-wheelchair" },
			{ name: "Happy Hour", icon: "fa-clock" },
			{ name: "Private Events", icon: "fa-champagne-glasses" },
		],
		followerGrowth: "+12%",
		followersList: [
			{
				id: 1,
				name: "Jennifer Adams",
				avatar:
					"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20a%20woman%20with%20long%20blonde%20hair%2C%20casual%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting%2C%20soft%20focus%2C%20natural%20looking%20headshot&width=40&height=40&seq=22&orientation=squarish",
				location: "Miami, FL",
				followedSince: "March 2025",
			},
			{
				id: 2,
				name: "Marcus Johnson",
				avatar:
					"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20a%20black%20man%20with%20short%20hair%2C%20casual%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting%2C%20soft%20focus%2C%20natural%20looking%20headshot&width=40&height=40&seq=23&orientation=squarish",
				location: "New York, NY",
				followedSince: "January 2025",
			},
			{
				id: 3,
				name: "Sophia Chen",
				avatar:
					"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20an%20asian%20woman%20with%20medium%20length%20black%20hair%2C%20casual%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting%2C%20soft%20focus%2C%20natural%20looking%20headshot&width=40&height=40&seq=24&orientation=squarish",
				location: "Los Angeles, CA",
				followedSince: "April 2025",
			},
		],
	},
	{
		id: 2,
		name: "Urban Spa Retreat",
		type: "Spa",
		location: "Downtown District, New York",
		image: sport,
		bookings: 18,
		rating: 4.9,
		followers: 875,
		isFollowed: false,
		revenue: "$24,500",
		status: "active",
		photos: [p1, p2, p3, p4, p5, p6],
		policies: {
			cancellation: "60 days notice required",
			insurance: "Required",
			cleaning: "$300 fee",
		},
		pricing: {
			base: "$400/hour",
			minimum: "$2000",
			deposit: "50%",
		},
		hours: [
			{ day: "monday", time: "4:00 PM - 12:00 AM" },
			{ day: "tuesday", time: "4:00 PM - 12:00 AM" },
			{ day: "wednesday", time: "4:00 PM - 1:00 AM" },
			{ day: "thursday", time: "4:00 PM - 1:00 AM" },
			{ day: "friday", time: "4:00 PM - 2:00 AM" },
			{ day: "saturday", time: "12:00 PM - 2:00 AM" },
			{ day: "sunday", time: "12:00 PM - 10:00 PM" },
		],
		address: "123 Urban Avenue, Downtown, City",
		phone: "+1 (555) 123-4567",
		website: "www.skylinerooftop.com",
		description:
			"Perched on the 20th floor with panoramic city views, Skyline Rooftop Lounge offers a sophisticated urban escape with craft cocktails, gourmet small plates, and live music events. Our open-air terrace and stylish indoor lounge create the perfect atmosphere for everything from casual happy hours to special celebrations. Known for our sunset DJ sessions and seasonal menu, we've become a favorite destination for both locals and visitors seeking an elevated social experience.",
		amenities: [
			{ name: "Outdoor Seating", icon: "fa-umbrella-beach" },
			{ name: "Live Music", icon: "fa-music" },
			{ name: "Craft Cocktails", icon: "fa-martini-glass-citrus" },
			{ name: "Reservations", icon: "fa-calendar-check" },
			{ name: "Valet Parking", icon: "fa-car" },
			{ name: "Wheelchair Accessible", icon: "fa-wheelchair" },
			{ name: "Happy Hour", icon: "fa-clock" },
			{ name: "Private Events", icon: "fa-champagne-glasses" },
		],
		followerGrowth: "+12%",
		followersList: [
			{
				id: 4,
				name: "Rachel Green",
				avatar:
					"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20a%20woman%20with%20medium%20brown%20hair%2C%20casual%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting%2C%20soft%20focus%2C%20natural%20looking%20headshot&width=40&height=40&seq=25&orientation=squarish",
				location: "New York, NY",
				followedSince: "February 2025",
			},
			{
				id: 5,
				name: "David Kim",
				avatar:
					"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20an%20asian%20man%20with%20glasses%2C%20casual%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting%2C%20soft%20focus%2C%20natural%20looking%20headshot&width=40&height=40&seq=26&orientation=squarish",
				location: "Boston, MA",
				followedSince: "March 2025",
			},
		],
	},
	{
		id: 3,
		name: "Downtown Event Hall",
		type: "Event Venue",
		location: "Business District, Chicago",
		image: sport,
		bookings: 7,
		rating: 4.6,
		followers: 520,
		isFollowed: true,
		revenue: "$24,500",
		status: "active",
		photos: [p1, p2, p3, p4, p5, p6],
		policies: {
			cancellation: "60 days notice required",
			insurance: "Required",
			cleaning: "$300 fee",
		},
		pricing: {
			base: "$400/hour",
			minimum: "$2000",
			deposit: "50%",
		},
		hours: [
			{ day: "monday", time: "4:00 PM - 12:00 AM" },
			{ day: "tuesday", time: "4:00 PM - 12:00 AM" },
			{ day: "wednesday", time: "4:00 PM - 1:00 AM" },
			{ day: "thursday", time: "4:00 PM - 1:00 AM" },
			{ day: "friday", time: "4:00 PM - 2:00 AM" },
			{ day: "saturday", time: "12:00 PM - 2:00 AM" },
			{ day: "sunday", time: "12:00 PM - 10:00 PM" },
		],
		address: "123 Urban Avenue, Downtown, City",
		phone: "+1 (555) 123-4567",
		website: "www.skylinerooftop.com",
		description:
			"Perched on the 20th floor with panoramic city views, Skyline Rooftop Lounge offers a sophisticated urban escape with craft cocktails, gourmet small plates, and live music events. Our open-air terrace and stylish indoor lounge create the perfect atmosphere for everything from casual happy hours to special celebrations. Known for our sunset DJ sessions and seasonal menu, we've become a favorite destination for both locals and visitors seeking an elevated social experience.",
		amenities: [
			{ name: "Outdoor Seating", icon: "fa-umbrella-beach" },
			{ name: "Live Music", icon: "fa-music" },
			{ name: "Craft Cocktails", icon: "fa-martini-glass-citrus" },
			{ name: "Reservations", icon: "fa-calendar-check" },
			{ name: "Valet Parking", icon: "fa-car" },
			{ name: "Wheelchair Accessible", icon: "fa-wheelchair" },
			{ name: "Happy Hour", icon: "fa-clock" },
			{ name: "Private Events", icon: "fa-champagne-glasses" },
		],
		followerGrowth: "+12%",
		followersList: [
			{
				id: 6,
				name: "Michael Scott",
				avatar:
					"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20a%20middle-aged%20man%20with%20short%20dark%20hair%2C%20business%20casual%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting%2C%20soft%20focus%2C%20natural%20looking%20headshot&width=40&height=40&seq=27&orientation=squarish",
				location: "Chicago, IL",
				followedSince: "December 2024",
			},
		],
	},
	{
		id: 4,
		name: "Rooftop Bar",
		type: "Bar",
		location: "Skyline Avenue, Los Angeles",
		image: sport,
		bookings: 32,
		rating: 4.7,
		followers: 1680,
		isFollowed: false,
		revenue: "$24,500",
		status: "active",
		photos: [p1, p2, p3, p4, p5, p6],
		policies: {
			cancellation: "60 days notice required",
			insurance: "Required",
			cleaning: "$300 fee",
		},
		pricing: {
			base: "$400/hour",
			minimum: "$2000",
			deposit: "50%",
		},
		hours: [
			{ day: "monday", time: "4:00 PM - 12:00 AM" },
			{ day: "tuesday", time: "4:00 PM - 12:00 AM" },
			{ day: "wednesday", time: "4:00 PM - 1:00 AM" },
			{ day: "thursday", time: "4:00 PM - 1:00 AM" },
			{ day: "friday", time: "4:00 PM - 2:00 AM" },
			{ day: "saturday", time: "12:00 PM - 2:00 AM" },
			{ day: "sunday", time: "12:00 PM - 10:00 PM" },
		],
		address: "123 Urban Avenue, Downtown, City",
		phone: "+1 (555) 123-4567",
		website: "www.skylinerooftop.com",
		description:
			"Perched on the 20th floor with panoramic city views, Skyline Rooftop Lounge offers a sophisticated urban escape with craft cocktails, gourmet small plates, and live music events. Our open-air terrace and stylish indoor lounge create the perfect atmosphere for everything from casual happy hours to special celebrations. Known for our sunset DJ sessions and seasonal menu, we've become a favorite destination for both locals and visitors seeking an elevated social experience.",
		amenities: [
			{ name: "Outdoor Seating", icon: "fa-umbrella-beach" },
			{ name: "Live Music", icon: "fa-music" },
			{ name: "Craft Cocktails", icon: "fa-martini-glass-citrus" },
			{ name: "Reservations", icon: "fa-calendar-check" },
			{ name: "Valet Parking", icon: "fa-car" },
			{ name: "Wheelchair Accessible", icon: "fa-wheelchair" },
			{ name: "Happy Hour", icon: "fa-clock" },
			{ name: "Private Events", icon: "fa-champagne-glasses" },
		],
		followerGrowth: "+12%",
		followersList: [
			{
				id: 7,
				name: "Emily Parker",
				avatar:
					"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20a%20young%20woman%20with%20red%20hair%2C%20casual%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting%2C%20soft%20focus%2C%20natural%20looking%20headshot&width=40&height=40&seq=28&orientation=squarish",
				location: "Los Angeles, CA",
				followedSince: "January 2025",
			},
			{
				id: 8,
				name: "James Wilson",
				avatar:
					"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20a%20man%20with%20short%20blonde%20hair%20and%20beard%2C%20casual%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting%2C%20soft%20focus%2C%20natural%20looking%20headshot&width=40&height=40&seq=29&orientation=squarish",
				location: "San Francisco, CA",
				followedSince: "February 2025",
			},
			{
				id: 9,
				name: "Olivia Martinez",
				avatar:
					"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20a%20latina%20woman%20with%20long%20dark%20hair%2C%20casual%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting%2C%20soft%20focus%2C%20natural%20looking%20headshot&width=40&height=40&seq=30&orientation=squarish",
				location: "San Diego, CA",
				followedSince: "April 2025",
			},
		],
	},
];
// Mock data for follower activity
const followerActivity = [
	{
		id: 1,
		name: "Jennifer Adams",
		avatar:
			"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20a%20woman%20with%20long%20blonde%20hair%2C%20casual%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting%2C%20soft%20focus%2C%20natural%20looking%20headshot&width=40&height=40&seq=31&orientation=squarish",
		action: "started following",
		spot: "Seaside Restaurant",
		time: "2 hours ago",
	},
	{
		id: 2,
		name: "Marcus Johnson",
		avatar:
			"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20a%20black%20man%20with%20short%20hair%2C%20casual%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting%2C%20soft%20focus%2C%20natural%20looking%20headshot&width=40&height=40&seq=32&orientation=squarish",
		action: "shared",
		spot: "Seaside Restaurant",
		time: "Yesterday",
	},
	{
		id: 3,
		name: "Rachel Green",
		avatar:
			"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20a%20woman%20with%20medium%20brown%20hair%2C%20casual%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting%2C%20soft%20focus%2C%20natural%20looking%20headshot&width=40&height=40&seq=33&orientation=squarish",
		action: "recommended",
		spot: "Urban Spa Retreat",
		time: "2 days ago",
	},
	{
		id: 4,
		name: "Emily Parker",
		avatar:
			"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20a%20young%20woman%20with%20red%20hair%2C%20casual%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting%2C%20soft%20focus%2C%20natural%20looking%20headshot&width=40&height=40&seq=34&orientation=squarish",
		action: "started following",
		spot: "Rooftop Bar",
		time: "3 days ago",
	},
];
// Mock data for events
const events = [
	{
		id: 1,
		title: "Summer Jazz Night",
		spot: "Rooftop Bar",
		date: "June 15, 2025",
		time: "7:00 PM - 11:00 PM",
		status: "upcoming",
		capacity: 200,
		booked: 145,
		type: "Music",
		image: img,
		price: 45,
		postedBy: {
			name: "Emma Wilson",
			role: "Manager",
			avatar:
				"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20a%20young%20woman%20with%20blonde%20hair%20in%20a%20ponytail%2C%20business%20casual%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting%2C%20soft%20focus%2C%20corporate%20headshot%20style&width=40&height=40&seq=20&orientation=squarish",
		},
	},
	{
		id: 2,
		title: "Corporate Networking Mixer",
		spot: "Downtown Event Hall",
		date: "June 20, 2025",
		time: "6:00 PM - 9:00 PM",
		status: "upcoming",
		capacity: 150,
		booked: 98,
		type: "Networking",
		image: img,
		price: 75,
		postedBy: {
			name: "David Miller",
			role: "Manager",
			avatar:
				"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20a%20young%20man%20with%20short%20blonde%20hair%2C%20business%20casual%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting%2C%20soft%20focus%2C%20corporate%20headshot%20style&width=40&height=40&seq=8&orientation=squarish",
		},
	},
	{
		id: 3,
		title: "Wine Tasting Experience",
		spot: "Seaside Restaurant",
		date: "June 25, 2025",
		time: "5:00 PM - 8:00 PM",
		status: "upcoming",
		capacity: 80,
		booked: 65,
		type: "Food & Wine",
		image: img,
		price: 95,
		postedBy: {
			name: "John Doe",
			role: "Owner",
			avatar:
				"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20a%20middle%20aged%20man%20in%20a%20suit%2C%20confident%20pose%2C%20business%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting&width=40&height=40&seq=39&orientation=squarish",
		},
	},
	{
		id: 4,
		title: "Wellness Workshop",
		spot: "Urban Spa Retreat",
		date: "June 30, 2025",
		time: "10:00 AM - 2:00 PM",
		status: "upcoming",
		capacity: 40,
		booked: 28,
		type: "Workshop",
		image: img,
		price: 120,
		postedBy: {
			name: "Jessica Lee",
			role: "Event Host",
			avatar:
				"https://readdy.ai/api/search-image?query=professional%20headshot%20of%20a%20woman%20with%20medium%20length%20red%20hair%2C%20business%20casual%20attire%2C%20neutral%20background%2C%20high%20quality%20portrait%2C%20professional%20lighting%2C%20soft%20focus%2C%20corporate%20headshot%20style&width=40&height=40&seq=9&orientation=squarish",
		},
	},
];
// Mock data
const user = {
	name: "Jessica Anderson",
	location: "San Francisco, CA",
	memberSince: "June 2023",
	email: "jessica.anderson@example.com",
	phone: "+1 (555) 123-4567",
	profileImage:
		"https://readdy.ai/api/search-image?query=professional%20portrait%20of%20a%20young%20woman%20with%20brown%20hair%20and%20friendly%20smile%2C%20high%20quality%2C%20professional%20photography%2C%20soft%20lighting%2C%20neutral%20background%2C%20looking%20at%20camera&width=200&height=200&seq=1&orientation=squarish",
	stats: {
		following: 28,
		eventsAttended: 47,
		reviews: 19,
	},
	loyaltyPoints: 3750,
	loyaltyTier: "Silver",
	loyaltyNextTier: "Gold",
	pointsToNextTier: 1250,
};
const pointsHistory = [
	{
		id: 1,
		date: "June 8, 2025",
		points: "+150",
		activity: "Attended Jazz Night",
		venue: "Blue Note Club",
		icon: "fa-music",
	},
	{
		id: 2,
		date: "June 5, 2025",
		points: "+200",
		activity: "Referred a friend",
		venue: "Platform Reward",
		icon: "fa-user-plus",
	},
	{
		id: 3,
		date: "May 29, 2025",
		points: "+100",
		activity: "First visit bonus",
		venue: "Skyline Rooftop Bar",
		icon: "fa-glass-martini",
	},
	{
		id: 4,
		date: "May 22, 2025",
		points: "-500",
		activity: "Redeemed for event ticket",
		venue: "Rewards Shop",
		icon: "fa-ticket-alt",
	},
	{
		id: 5,
		date: "May 15, 2025",
		points: "+75",
		activity: "Left a review",
		venue: "The Grand Hall",
		icon: "fa-star",
	},
];
const followedVenues = [
	{
		id: 1,
		name: "Blue Note Jazz Club",
		category: "Music Venue",
		image: sport,
		location: "Oceanfront Drive, Miami",
		isOpen: true,
		rating: 4.5,
		reviews: 164,
		latestEvent: "Jazz Fusion Night - June 15",
	},
	{
		id: 2,
		name: "Skyline Rooftop Bar",
		category: "Bar",
		image: sport,
		location: "Oceanfront Drive, Miami",
		isOpen: true,
		rating: 4.5,
		reviews: 164,
		latestEvent: "Sunset Cocktail Party - June 20",
	},
	{
		id: 3,
		name: "The Grand Hall",
		category: "Event Space",
		image: sport,
		location: "Oceanfront Drive, Miami",
		isOpen: true,
		rating: 4.5,
		reviews: 164,
		latestEvent: "Summer Gala - July 8",
	},
	{
		id: 4,
		name: "Pixel Arcade",
		category: "Arcade",
		image: sport,
		location: "Oceanfront Drive, Miami",
		isOpen: true,
		rating: 4.5,
		reviews: 164,
		latestEvent: "Retro Gaming Tournament - June 25",
	},
	{
		id: 5,
		name: "Sacred Heart Chapel",
		category: "Religious",
		image: sport,
		location: "Oceanfront Drive, Miami",
		isOpen: true,
		rating: 4.5,
		reviews: 164,
		latestEvent: "Community Choir - Sundays",
	},
	{
		id: 6,
		name: "Warehouse 21",
		category: "Nightclub",
		image: sport,
		location: "Oceanfront Drive, Miami",
		isOpen: true,
		rating: 4.5,
		reviews: 164,
		latestEvent: "Electronic Music Night - June 18",
	},
];
const upcomingEvents = [
	{
		id: 1,
		name: "Jazz Fusion Night",
		date: "June 15, 2025 • 8:00 PM",
		venue: "Blue Note Jazz Club",
		image: img,
	},
	{
		id: 2,
		name: "Sunset Cocktail Party",
		date: "June 20, 2025 • 6:30 PM",
		venue: "Skyline Rooftop Bar",
		image: img,
	},
	{
		id: 3,
		name: "Retro Gaming Tournament",
		date: "June 25, 2025 • 7:00 PM",
		venue: "Pixel Arcade",
		image: img,
	},
];
const pastEvents = [
	{
		id: 1,
		name: "Wine Tasting Experience",
		date: "May 30, 2025 • 7:00 PM",
		venue: "Vineyard Lounge",
		image: img,
		rated: true,
		rating: 5,
	},
	{
		id: 2,
		name: "Comedy Night Special",
		date: "May 22, 2025 • 8:30 PM",
		venue: "Laugh Factory",
		image: img,
		rated: true,
		rating: 4,
	},
	{
		id: 3,
		name: "Art Gallery Opening",
		date: "May 15, 2025 • 6:00 PM",
		venue: "Modern Art Space",
		image: img,
		rated: false,
	},
];
const trendingEvents = [
	{
		id: 1,
		title: "Summer Jazz Festival",
		date: "June 15, 2025",
		time: "6:00 PM",
		location: "Central Park",
		category: "music",
		attendees: 1240,
		image: img,
	},
	{
		id: 2,
		title: "Food Truck Rally",
		date: "June 10, 2025",
		time: "12:00 PM",
		location: "Downtown Square",
		category: "food",
		attendees: 890,
		image: img,
	},
	{
		id: 3,
		title: "NBA Finals Viewing Party",
		date: "June 8, 2025",
		time: "8:00 PM",
		location: "Sports Bar & Grill",
		category: "sports",
		attendees: 650,
		image: img,
	},
	{
		id: 4,
		title: "Modern Art Exhibition",
		date: "June 12, 2025",
		time: "10:00 AM",
		location: "Metropolitan Gallery",
		category: "arts",
		attendees: 520,
		image: img,
	},
	{
		id: 5,
		title: "Rooftop Cocktail Night",
		date: "June 7, 2025",
		time: "9:00 PM",
		location: "Skyline Lounge",
		category: "bar",
		attendees: 380,
		image: img,
	},
];

export {
	spots,
	followerActivity,
	messages,
	mySpots,
	staffMembers,
	staffTasks,
	upcomingBookings,
	events,
	pastEvents,
	upcomingEvents,
	followedVenues,
	pointsHistory,
	user,
	trendingEvents,
};
